<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>MiSideVR</AssemblyName>
		<RootNamespace>MiSideVR</RootNamespace>
		<TargetFramework>net6.0</TargetFramework>
		<Version>1.0.0</Version>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<InformationalVersion>1.0b-pre1</InformationalVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.697" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\MiSide\BepInEx\interop\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\MiSide\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="SteamVR_Standalone_IL2CPP">
      <HintPath>..\..\..\..\Documents\VS2022-PROJ\SteamVR_Standalone_IL2CPP.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Postprocessing.Runtime">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\MiSide\BepInEx\interop\Unity.Postprocessing.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\MiSide\BepInEx\interop\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\MiSide\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\MiSide\BepInEx\interop\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\MiSide\BepInEx\interop\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\MiSide\BepInEx\interop\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\MiSide\BepInEx\interop\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VRModule">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\MiSide\BepInEx\interop\UnityEngine.VRModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.XRModule">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\MiSide\BepInEx\interop\UnityEngine.XRModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
